PRINT @200 /* ~Processing Shadows of Amn components...~*/

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/bg2/d~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/bg2/baf~

COPY_EXISTING ~ar0312.are~ ~override/xaexpl01.are~
WRITE_ASCII 0x94 ~~ #8 // remove the area script
LPF xa_delete_are_actors END
LPF xa_delete_are_triggers END

COPY_EXISTING ~ar0416.are~ ~override/xaexpl02.are~
WRITE_ASCII 0x94 ~~ #8 // remove the area script
LPF xa_delete_are_actors END
LPF xa_delete_are_triggers END