IF
	True()
THEN
	RESPONSE #100
		CutSceneID(Player1)
		ActionOverride("XACOREX3", MoveToPoint([420.200]))
		Wait(3)
		ActionOverride("XACOREX3", FaceObject("XANEOMA"))
		SmallWait(5)
		DisplayStringHead("XACOREX3", @0)
		Wait(1)
		ActionOverride("XANEOMA", FaceObject("XACOREX3")
		Wait(1)
		ActionOverride("XACOREX3", MoveToPoint([630.280]))
		ActionOverride("XANEOMA", MoveToPoint([625.305]))
		Wait(1)
		MoveToPoint([540.285])
		ActionOverride("XACOREX3", StartDialog("XACOREX3", Player1))
END