IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		StorePartyLocations()
		FadeToColor([30.0],0)
		Wait(3)
		ZoomLock(TRUE)
		LeaveAreaLUAPanic("XAEXPL03","",[350.160],S) 
		LeaveAreaLUA("XAEXPL03","",[350.160],S)
		Explore()
		CreateCreature("XACOREX3",[350.180],N) 
		TextScreen("XAEX03FS")
		FadeFromColor([30.0],0)
		SmallWait(1)
		SetGlobal("XA_LCE_Sex3Intro", "GLOBAL", 1)
		EndCutSceneMode()
END