IF
	True()
THEN
	RESPONSE #100
		CutSceneID(Player1)
		ActionOverride("XACOREX3", MoveToPoint([310.250]))
		Wait(5)
		DisplayStringHead("XACOREX3", @0)
		Wait(1)
		ActionOverride("XANEOMA", FaceObject("XACOREX3")
		Wait(1)
		ActionOverride("XACOREX3", MoveToPoint([630.280]))
		ActionOverride("XANEOMA", MoveToPoint([625.305]))
		Wait(1)
		MoveToPoint([540.285])
		ActionOverride("XANEOMA", StartDialog("XANEOMA", Player1))
END