IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("XA_LC_XAEXPL02", "GLOBAL", 1)
		StorePartyLocations()
		FadeToColor([30.0],0)
		Wait(3)
		ZoomLock(TRUE)
		LeaveAreaLUA("XAEXPL02","",[460.295],NW)
		ActionOverride("XACORWIN", LeaveAreaLUA("XAEXPL02","",[425.270],SE)) 
		Explore()
		FadeFromColor([30.0],0)
		FaceObject("XACORWIN")
		SmallWait(1)
		ActionOverride("XACORWIN", FaceObject(Player1))
		Wait(2)
		ActionOverride("XACORWIN", StartDialog("XACORWIJ", Player1))
END